Script started on Tue 22 Mar 2016 02:43:48 AM CST
[1m[3m%[23m[1m[0m                                                                                                                          ]2;kh@debian:~/Coding/PD2/lab2[0m[23m[24m[J[38;5;140mkh@debian[39m [38;5;110m~/Coding/PD2/lab2[39m $ [K[?1h=ffile.   f  ccat file.im n[?1l>
]2;kh@debian:~/Coding/PD2/lab2170 68
160 85
162 43
167 80
192 58
0   0
[1m[3m%[23m[1m[0m                                                                                                                          ]2;kh@debian:~/Coding/PD2/lab2[0m[23m[24m[J[38;5;140mkh@debian[39m [38;5;110m~/Coding/PD2/lab2[39m $ [K[?1h=../fil   BMI[?1l>
]2;kh@debian:~/Coding/PD2/lab2[1m[3m%[23m[1m[0m                                                                                                                          ]2;kh@debian:~/Coding/PD2/lab2[0m[23m[24m[J[38;5;140mkh@debian[39m [38;5;110m~/Coding/PD2/lab2[39m $ [K[?1h=ccat file.out[?1l>
]2;kh@debian:~/Coding/PD2/lab223.53  Normal
33.2   Obese Class I (Moderately obese)
16.38  Underweight
28.69  Overweight
15.73  Severely underweight
[1m[3m%[23m[1m[0m                                                                                                                          ]2;kh@debian:~/Coding/PD2/lab2[0m[23m[24m[J[38;5;140mkh@debian[39m [38;5;110m~/Coding/PD2/lab2[39m $ [K[?1h=

Script done on Tue 22 Mar 2016 02:44:18 AM CST
